# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_service_pb2 as ml__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MlInferenceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbeddings = channel.unary_unary(
                '/ml_service.MlInference/GenerateEmbeddings',
                request_serializer=ml__service__pb2.EmbedRequest.SerializeToString,
                response_deserializer=ml__service__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.ExtractTriplets = channel.unary_unary(
                '/ml_service.MlInference/ExtractTriplets',
                request_serializer=ml__service__pb2.ExtractRequest.SerializeToString,
                response_deserializer=ml__service__pb2.ExtractResponse.FromString,
                _registered_method=True)
        self.IngestBatch = channel.unary_unary(
                '/ml_service.MlInference/IngestBatch',
                request_serializer=ml__service__pb2.BatchIngestRequest.SerializeToString,
                response_deserializer=ml__service__pb2.BatchIngestResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ml_service.MlInference/HealthCheck',
                request_serializer=ml__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ml__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MlInferenceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractTriplets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MlInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddings,
                    request_deserializer=ml__service__pb2.EmbedRequest.FromString,
                    response_serializer=ml__service__pb2.EmbedResponse.SerializeToString,
            ),
            'ExtractTriplets': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractTriplets,
                    request_deserializer=ml__service__pb2.ExtractRequest.FromString,
                    response_serializer=ml__service__pb2.ExtractResponse.SerializeToString,
            ),
            'IngestBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestBatch,
                    request_deserializer=ml__service__pb2.BatchIngestRequest.FromString,
                    response_serializer=ml__service__pb2.BatchIngestResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ml__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ml__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_service.MlInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml_service.MlInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MlInference:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MlInference/GenerateEmbeddings',
            ml__service__pb2.EmbedRequest.SerializeToString,
            ml__service__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractTriplets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MlInference/ExtractTriplets',
            ml__service__pb2.ExtractRequest.SerializeToString,
            ml__service__pb2.ExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MlInference/IngestBatch',
            ml__service__pb2.BatchIngestRequest.SerializeToString,
            ml__service__pb2.BatchIngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MlInference/HealthCheck',
            ml__service__pb2.HealthCheckRequest.SerializeToString,
            ml__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
