# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\nml_service\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"2\n\rEmbedResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x11\n\tdimension\x18\x02 \x01(\x05\"\x1e\n\x0e\x45xtractRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"=\n\x07Triplet\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t\"8\n\x0f\x45xtractResponse\x12%\n\x08triplets\x18\x01 \x03(\x0b\x32\x13.ml_service.Triplet\"\x14\n\x12HealthCheckRequest\"@\n\x13HealthCheckResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.ml_service.ServingStatus*:\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\xf4\x01\n\x0bMlInference\x12I\n\x12GenerateEmbeddings\x12\x18.ml_service.EmbedRequest\x1a\x19.ml_service.EmbedResponse\x12J\n\x0f\x45xtractTriplets\x12\x1a.ml_service.ExtractRequest\x1a\x1b.ml_service.ExtractResponse\x12N\n\x0bHealthCheck\x12\x1e.ml_service.HealthCheckRequest\x1a\x1f.ml_service.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVINGSTATUS']._serialized_start=355
  _globals['_SERVINGSTATUS']._serialized_end=413
  _globals['_EMBEDREQUEST']._serialized_start=32
  _globals['_EMBEDREQUEST']._serialized_end=60
  _globals['_EMBEDRESPONSE']._serialized_start=62
  _globals['_EMBEDRESPONSE']._serialized_end=112
  _globals['_EXTRACTREQUEST']._serialized_start=114
  _globals['_EXTRACTREQUEST']._serialized_end=144
  _globals['_TRIPLET']._serialized_start=146
  _globals['_TRIPLET']._serialized_end=207
  _globals['_EXTRACTRESPONSE']._serialized_start=209
  _globals['_EXTRACTRESPONSE']._serialized_end=265
  _globals['_HEALTHCHECKREQUEST']._serialized_start=267
  _globals['_HEALTHCHECKREQUEST']._serialized_end=287
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=289
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=353
  _globals['_MLINFERENCE']._serialized_start=416
  _globals['_MLINFERENCE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
